apiVersion: v1
kind: Service
metadata:
  name: pd0
  namespace: tidb
  labels:
    appname: pd0-service
spec:
  ports: 
  - name: make1
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: make2
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    deployment: pd0
---
apiVersion: v1
kind: Service
metadata:
  name: pd1
  namespace: tidb
  labels:
    appname: pd1-service
spec:
  ports: 
  - name: port-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: port-2380
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    deployment: pd1

---
apiVersion: v1
kind: Service
metadata:
  name: pd2
  namespace: tidb
  labels:
    appname: pd2-service
spec:
  ports: 
  - name: port-2379
    port: 2379
    protocol: TCP
    targetPort: 2379
  - name: port-2380
    port: 2380
    protocol: TCP
    targetPort: 2380
  selector:
    deployment: pd2

---
apiVersion: v1
kind: Service
metadata:
  name: tikv1
  namespace: tidb
  labels:
    appname: tikv1-service
spec:
  ports: 
  - name: port-20160
    port: 20160
    protocol: TCP
    targetPort: 20160
  selector:
    deployment: tikv1