apiVersion: v1
description: tidb-cluster Helm chart for Kubernetes using tidb-operator
name: tidb-cluster
version: 0.1.0
home: https://github.com/pingcap/tidb-operator
sources:
  - https://github.com/pingcap/tidb-operator
keywords:
  - newsql
  - htap
  - database
  - mysql
  - raft
