{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  grafana-username: {{ .Values.secrets.grafanaUsername | default "admin" | b64enc }}
  grafana-password: {{ .Values.secrets.grafanaPassword | default "admin" | b64enc }}
{{- end }}
