apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: tidb-controller-manager
  labels:
    app: tidb-operator
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      app: tidb-operator
      name: tidb-controller-manager
  template:
    metadata:
      labels:
        app: tidb-operator
        name: tidb-controller-manager
    spec:
    {{- if .Values.rbac.create }}
      serviceAccount: tidb-controller-manager
    {{- end }}
      containers:
      - name: tidb-operator
        image: {{ .Values.operatorImage }}
        resources:
{{ toYaml .Values.controllerManager.resources | indent 12 }}
        command:
          - /usr/local/bin/tidb-controller-manager
          - -L={{ .Values.controllerManager.logLevel }}
          - -rbac-enabled={{ .Values.rbac.create }}
          - -test-mode={{ .Values.testMode | default false }}
          - -review-enabled={{ .Values.reviewEnabled | default false }}
          - -resync-duration={{ .Values.resyncDuration }}
          - -external-traffic-policy={{ .Values.controllerManager.serviceExternalTrafficPolicy | default "Cluster" }}
        env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: timezone
            mountPath: /etc/localtime
      volumes:
      - name: timezone
        hostPath:
          path: /etc/localtime
