{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Namespace }}:tidb-controller-manager
subjects:
- kind: ServiceAccount
  name: tidb-controller-manager
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: tidb-scheduler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}:tidb-controller-manager
  apiGroup: rbac.authorization.k8s.io
{{- end }}
