apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: tidb-scheduler-policy
  labels:
    app: tidb-operator
data:
  policy.cfg: |-
    {
            "kind" : "Policy",
            "apiVersion" : "v1",
            "predicates": [
                    {"name": "MatchNodeSelector"},
                    {"name": "PodFitsResources"},
                    {"name": "PodFitsHostPorts"},
                    {"name": "HostName"},
                    {"name": "NoDiskConflict"},
                    {"name": "PodToleratesNodeTaints"},
                    {"name": "CheckNodeMemoryPressure"},
                    {"name": "CheckNodeDiskPressure"},
                    {"name": "MatchInterPodAffinity"},
                    {"name": "GeneralPredicates"}
            ],
            "priorities": [
                    {"name": "EqualPriority", "weight": 1},
                    {"name": "ImageLocalityPriority", "weight": 1},
                    {"name": "LeastRequestedPriority", "weight": 1},
                    {"name": "BalancedResourceAllocation", "weight": 1},
                    {"name": "SelectorSpreadPriority", "weight": 1},
                    {"name": "NodePreferAvoidPodsPriority", "weight": 1},
                    {"name": "NodeAffinityPriority", "weight": 1},
                    {"name": "TaintTolerationPriority", "weight": 1},
                    {"name": "MostRequestedPriority", "weight": 1}
            ],
            "extenders": [
                    {
                            "urlPrefix": "http://127.0.0.1:10262/scheduler",
                            "filterVerb": "filter",
                            "weight": 1,
                            "httpTimeout": 30000000000,
                            "enableHttps": false
                    }
            ]
    }
